### ISSUE TITLE
d1_mini won't build.

### ISSUE THREAD

**Issue by rogerw-gh** [synman/BME280#1]
Hi there, having trouble compiling for a Wemos D1-mini clone,  fails at finding ESP8266WiFi.h,  tried googling for results, including deleting build libraries and a vanilla reinstall of VS-Code/PlatformIO - still no joy.  Is there a reason for the compile switch ESP32, running a build using the default platformio.ini builds the ESP32 but fails on the d1_min - the main.h include file uses alternative libraries for the two boards using the esp32 compile option.
Thanks.

**Comment by synman** [comment]
What OS are you running?  I'll pull this repo down on an alternate machine today and take a look.

The platform switch is used to trigger some precompiler switches where the framework between esp8266 and ESP32 differs.

**Comment by synman** [comment]
absolutely bone dry / brand spanking new environment on an intel mac mini running Sonoma:

![Screenshot 2024-01-24 at 10 01 04 AM](https://github.com/synman/BME280/assets/1299716/0f86597c-b0b7-458b-9207-a859517b7705)

**Comment by rogerw-gh** [comment]
> What OS are you running? I'll pull this repo down on an alternate machine today and take a look.
> 
> The platform switch is used to trigger some precompiler switches where the framework between esp8266 and ESP32 differs.

Tried Ubuntu 20.04.6 LTS where I do most building/compiling, existing VSCode install, tried cleaning and Full Clean in VSC -  
Also tried Mac OS Ventura on a MacPro Xeon with brand new VSCode install and vanilla platformIO config.  Googled the reported error and tried all sorts of additional libraries/deleted cache directories manually...  

Forced a build with default_envs set to d1_mini on Ubuntu.

Mac tries to build d1_mini then esp32dev, d1 fails, esp32 builds... :-(.  Always fall over at same place, hopefully screenshot will attach.  Time is GMT.
![Screenshot from 2024-01-24 16-24-58](https://github.com/synman/BME280/assets/19221398/665a9f67-b104-43d6-96c2-df8702517f4f)


!

**Comment by synman** [comment]
Give me your entire build log, and to confirm you're selecting build from the pio d1mini build menu?

**Comment by rogerw-gh** [comment]
Missed the update :-(.  Attached is a fresh build log from PlatformIO and a copy of the terminal output from Building the d1_mini task - and yes I am using the Build button from below the General folder beneath d1_mini.
[project update.log](https://github.com/synman/BME280/files/14072834/project.update.log)
[failed_build_log.txt](https://github.com/synman/BME280/files/14072835/failed_build_log.txt)
Both created on Ubuntu LTS workstation and copied/pasted.

**Comment by synman** [comment]
let's try this...

Update the BME280's project platformio.ini file like so:

```
[env:d1_mini]
platform = espressif8266@4.2.1
board = d1_mini
lib_ldf_mode = deep+
```

notice I added `lib_ldf_mode = deep+` to the d1_mini build type.

**Comment by synman** [comment]
and another option, with, or without, changing the ldf mode to deep+:

```
[env:d1_mini]
platform = espressif8266@4.2.1
board = d1_mini
lib_ldf_mode = deep+

...

lib_deps = 
    ESP8266Wifi
    ${env.lib_deps}
```

notice we are defining `ESP8266Wifi` explicitly here.   It should show up as as a top level dependency before resolving any others:

```
Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESP-Bootstrap @ 1.1.1
|-- Adafruit BME280 Library @ 2.2.4+sha.9412f3d
|-- PubSubClient @ 2.8.0+sha.2d228f2
|-- home-assistant-integration @ 2.0.0+sha.93787b2
|-- TelnetSpy @ 1.4.0
|-- ArduinoOTA @ 1.0
|-- Wire @ 1.0
|-- SPI @ 1.0
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESP8266TimerInterrupt @ 1.6.0
|-- DNSServer @ 1.1.1
|-- EEPROM @ 1.0
|-- LittleFS @ 0.1.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- Hash @ 1.0
|-- ElegantOTA @ 3.1.0
|-- Adafruit BusIO @ 1.15.0
|-- Adafruit Unified Sensor @ 1.1.14
|-- ESP8266HTTPClient @ 1.2
```
Something that I noticed was that your build is resolving ESP8266WiFi  as its last dependency too:
```
Dependency Graph
|-- ESP-Bootstrap @ 1.1.1
|-- Adafruit BME280 Library @ 2.2.4+sha.9412f3d
|-- PubSubClient @ 2.8.0+sha.2d228f2
|-- home-assistant-integration @ 2.0.0+sha.93787b2
|-- ESP8266HTTPClient @ 1.2
|-- ESP8266WiFi @ 1.0
```
With these changes, two things will happen:
* ESP8266WifI will be the first dependency resolved for the d1_mini build variant 
* The compiler will search deep within the framework to resolve all dependencies

**Comment by rogerw-gh** [comment]
I'd tried deep+ mode and most of the obvious results DuckDuckGo / Google returned. 

Tried this -  https://github.com/Hypfer/esp8266-vindriktning-particle-sensor, built OK and worked without sensor attached..

Gave up and bought some Wemos ESP32 d1 mini clones, which built but restarted because LittleFS was borked [another story], still working on that.

Most recent results:

Explicit ESP8266 library, dependency element..

Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESP-Bootstrap @ 1.1.1
|-- Adafruit BME280 Library @ 2.2.4+sha.9412f3d
|-- PubSubClient @ 2.8.0+sha.2d228f2
|-- home-assistant-integration @ 2.0.0+sha.93787b2
|-- ESP8266HTTPClient @ 1.2
Building in release mode
Compiling .pio/build/d1_mini/src/main.cpp.o

[FAILED]

With deep+ and lib_deps lots of errors.
Removed and performed deep clean.

**Comment by rogerw-gh** [comment]
Rerun and validate line 82 in Bootstrap.h, in ESP-Bootstrap, after checking whether PlatformIO was case sensitive [it doesn't appear to be] because: 
.pio/libdeps/d1_mini/ESP-Bootstrap/include/Bootstrap.h:82:14: fatal error: ESP8266Wifi.h: No such file or directory

Change Bootstrap.h line 82 to read
    #include <ESP8266WiFi.h> , capital F.

Unfortunately, doing a Full Clean erases / replaces Bootstrap.h with the original.
So after fixing the name of the file in ESP-Bootstrap/include/Bootstrap.h, we get a result, a build :-).

**Comment by rogerw-gh** [comment]
N.B. there is no sensor attached, but connecting from an iPhone results in a crash / page dump [as does the Wemos D1 mini clone] and system restart.  So the soldering iron will be coming out later, just to see what happens..


N.B. iPhone is set to generate new MAC address 
<snip>
12:50:07.806 > SoftAP [bme280-env-ssk:255.255.255.0,gw:192.168.4.1)
12:50:07.806 > bcn 100
12:50:07.806 > 
12:50:07.806 > SoftAP [bme280-env-ssk:255.255.255.0,gw:192.168.4.1)
12:50:07.806 > bcn 100
12:50:07.806 > 
12:50:07.806 > SoftAP [bme280-env-sensor] started
12:50:07.806 > 
12:50:07.806 >     Hostname: bme280-env-sensor
12:50:07.806 > Connected to: bme280-env-sensor
12:50:07.806 >   IP address: 192.168.4.1
12:50:07.806 >         RSSI: 31 dB
12:50:07.806 > 
12:50:07.806 > ArduinoOTA started
12:50:07.806 > ElegantOTA started
12:50:07.806 > HTTP server started
12:50:07.806 > Watchdog started
12:50:07.806 > 
12:50:07.806 > Could not find a valid BME280 sensor, check wiring!
12:50:07.806 > 
12:50:07.806 > System Ready
12:50:07.806 > 
12:50:07.806 > Sea Level hPa = -32768.00
12:50:07.806 > Gathered Sample #1
12:50:10.738 > add 1
12:50:10.738 > aid 1
station: ee:11:64:1e:f4:11 join, AID = 1
12:50:15.135 > Fatal exception 28(LoadProhibitedCause):
12:50:15.135 > epc1=0x4020d449, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
12:50:15.136 > 
12:50:15.136 > --------------- CUT HERE FOR EXCEPTION DECODER ---------------
12:50:15.137 > 
12:50:15.137 > Exception (28):
12:50:15.137 > epc1=0x4020d449 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000
12:50:15.191 > 
12:50:15.191 > LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
12:50:15.191 >   epc1=0x4020d449 in std::_Function_handler<void (AsyncWebServerRequest*), Bootstrap::wireWebServerAndPaths()::{lambda(AsyncWebServerRequest*)#3}>::_M_invoke(std::_Any_data const&, AsyncWebServerRequest*&&) at Bootstrap.cpp:?
12:50:15.191 > 
12:50:15.191 > >>>stack>>>
12:50:17.279 > 
12:50:17.279 > ctx: sys <snip>

Oh well, but the original issue is closed.
